bill table styling
douglas86/january-hackathon-team8 pull request #56
Opened 2024-01-20 21:08 UTC by samuelandersoncodes

styled bill table for responsiveness

2024-01-20 23:01 UTC, douglas86 requested changes
Is this branch updated with the main branch

2024-01-21 20:00 UTC, douglas86 commented on calculated_hackers/settings.py
Lines 43, 49, 51 needs to be removed.

2024-01-21 20:01 UTC, douglas86 commented on calculated_hackers/settings.py
> +=======
Lines 43, 49 and 51 needs to be removed

2024-01-21 20:02 UTC, samuelandersoncodes commented on calculated_hackers/settings.py
> +=======
ok

2024-01-21 20:03 UTC, douglas86 commented on templates/base.html
> +    <link rel="stylesheet" href="{% static 'css/media_queries.css' %}">
these have already been added at line 40 to 42. These can then be deleted.

2024-01-21 20:19 UTC, closed without merging